// packages/react-app/src/main.tsx
import { initApp } from "@openlooks/core/utils/init";
import "@openlooks/styles/index.css";
import React from "react";
import ReactDOM from "react-dom/client";
import { App } from "./App";

initApp();

ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

// packages/solid/src/main.tsx
/* @refresh reload */
import { render } from 'solid-js/web';
import App from './site/App';
import { initApp } from './utils/init';

import '@openlooks/styles';
import './site/index.css';
import './site/prism-light.css';

initApp();

render(() => <App />, document.getElementById('root') as HTMLDivElement);
